apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.project }}-{{ .Values.application.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    path: {{ .Values.application.path }}
    repoURL: {{ .Values.application.repository }}
    targetRevision: {{ .Values.application.targetRevision }}
    helm:
      version: v3
      values: |
        env:
          template: default
        {{- if .Values.preview }}
        image:
          tag: {{ .Values.application.image.tag }}
        {{- else }}
        {{- end }}
        {{- if .Values.application.values }}
        {{ .Values.application.values | nindent 8 }}
        {{- end }}
  destination:
    namespace: {{ .Values.application.destination.namespace }}
    server: {{ .Values.application.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
