application:
  name: example
  repository: https://github.com/unbounded-tech/workflows-gitops.git
  targetRevision: main
  path: .gitops/deploy/helm
  values: ""
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  image:
    tag: latest

project: default

preview: false