name: github-release
on:
  workflow_call:
    inputs: 
      container:
        type: boolean
        required: false
      helm:
        type: boolean
        required: false
    secrets:
      GH_ORG_TOKEN:
        required: true
    
jobs:

  release:
    name: Github Release
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: fetch tags
      run: |
        git fetch --tags

    - name: previous tag
      run: |
        previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        echo "previous_tag=$previous_tag" >> $GITHUB_ENV

    - name: Version
      id: version
      uses: paulhatch/semantic-version@v4.0.3
      with:
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "feat"
        bump_each_commit: true

    # - name: Generate changelog
    #   id: changelog
    #   if: env.previous_tag
    #   uses: jaywcjlove/changelog-generator@main
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Conventional Changelog
      id: changelog
      if: env.previous_tag
      run: >-
        echo "changelog=$(
          npx conventional-changelog-cli -p angular
        )" >> $GITHUB_OUTPUT

    - run: |
        echo "${{ steps.changelog.outputs.changelog }}"
      
    - name: Update image.tag in helm values (Optional)
      if: inputs.container
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag = "${{ steps.version.outputs.version_tag }}"' helm/values.yaml
    
    - name: Update version in helm chart (Optional)
      if: inputs.helm
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.version = "${{ steps.version.outputs.version_tag }}"' helm/Chart.yaml

    - name: Commit changes (Optional)
      if: inputs.helm || inputs.container
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -am "chore: set version to ${{ steps.version.outputs.version_tag }}"
        git tag -a ${{ steps.version.outputs.version_tag }} -m "${{ steps.version.outputs.version_tag }}"
    
    - name: Push to tag
      uses: ad-m/github-push-action@master
      if: always()
      with:
        github_token: ${{ secrets.GH_ORG_TOKEN }}
        branch: ${{ steps.version.outputs.version_tag }}
        tags: true

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version_tag }}
        generate_release_notes: true
        body: |
          ${{ steps.changelog.outputs.changelog }}