name: gitops-preview

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: false
      project:
        type: string
        required: true
      environment_repository:
        required: true
        type: string
      container:
        required: false 
        type: boolean
      integrationTestsContainer:
        required: false 
        type: boolean
      comment:
        required: false
        type: string
        default: |
          Your preview environment has been published! :rocket:
    secrets:
      GH_ORG_TOKEN:
        required: true

jobs:

  gitops-preview:
    name: Gitops Preview
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Set up QEMU
      if: inputs.container
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: inputs.container
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      if: inputs.container
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      if: inputs.container
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ env.REPO }}

    - name: Build and push Docker image
      if: inputs.container
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ghcr.io/${{ env.REPO }}:pr-${{ github.event.pull_request.number }}-${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ env.REPO }}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ env.REPO }}:buildcache,mode=max

    - name: Build and push integration tests docker image
      if: inputs.integrationTestsContainer
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./jest.integration.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.REPO }}-integration-tests:pr-${{ github.event.pull_request.number }}-${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ env.REPO }}-integration-tests:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ env.REPO }}-integration-tests:buildcache,mode=max

    - name: Setup Helm
      uses: azure/setup-helm@v3
    
    - name: Checkout Preview Environments Project
      uses: actions/checkout@v3
      with: 
        path: previews
        repository: ${{ inputs.environment_repository }}
        persist-credentials: false

    - name: Create Preview from Helm template
      run: |
        mkdir -p previews/helm/templates
        helm template preview/helm/ \
          --set name=${{ inputs.name || github.event.repository.name }} \
          --set pr=pr-${{ github.event.pull_request.number }} \
          --set tag=pr-${{ github.event.pull_request.number }}-${{ github.sha }} \
          --set headRef=${{ github.head_ref }} \
          --set project=${{ inputs.project }} \
          --set repository=${GITHUB_REPOSITORY} \
          > previews/helm/templates/${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}.yaml

    - name: Commit Preview Env Changes
      run: |
        cd previews

        if output=$(git status --porcelain) && [ -z "$output" ]; then
          # Working directory clean

          echo "No changes to commit"
        else 
          # Uncommitted changes

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"   
          git add -A
          git commit -m "feat(${{ github.event.repository.name }}): ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }} ${{ github.sha }}"
        fi

    - name: Push Preview Env Changes
      uses: ad-m/github-push-action@master
      with:
        directory: previews
        github_token: ${{ secrets.GH_ORG_TOKEN }}
        repository: ${{ inputs.environment_repository }}

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Your preview environment

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ${{ inputs.comment }}
        edit-mode: replace
